// Error codes
#define LOGGER_HUFFMAN_OK  						0
#define ERR_LOGGER_HUFFMAN_SEGMENTATION_FAULT	-700
#define ERR_LOGGER_HUFFMAN_ABRT           		-701
#define ERR_LOGGER_HUFFMAN_COMMAND_LINE	   		-702
#define ERR_LOGGER_HUFFMAN_INSUFFICIENT_MEMORY	-703
#define ERR_LOGGER_HUFFMAN_INSUFFICIENT_PARAMS	-704
#define ERR_LOGGER_HUFFMAN_PARAM_INVALID		-705
#define ERR_LOGGER_HUFFMAN_NO_DATA      		-706
#define ERR_LOGGER_HUFFMAN_INVALID_PACKET		-707

#define ERR_MESSAGE								"Error "
#define ERR_DEBUG								"Info "
#define ERR_WARNING								"Warning "
