name: Build Automake C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: clean
      run: make clean
    - name: make
      run: make
    - name: check
      run: make check
    - name: distcheck
      run: make distcheck
